import 'package:sepapka/model_layer/models/question.dart';

final questionListDB = [
  Question(
      id: "epoDl89w4G4cRcNFrG7Y",
      q: "Uziemiony przewód instalacji, przez który w warunkach normalnych nie płynie prąd roboczy to przewód:",
      a1: "ochronny PE",
      a2: "neutralny N",
      a3: "fazowy L",
      a4: "środkowy M",
      labels: ["sieci niskiego napięcia"],
      level: 1,
      assetPath: ""),
  Question(
      id: "eQgeDoaX37agSq5ki91l",
      q: "Urządzenia III klasy ochronności mogą być zasilanie napięciem:",
      a1: "SELV lub PELV",
      a2: "przemiennym do 230 V",
      a3: "stałym do 230 V",
      a4: "przemiennym do 1 kV",
      labels: ["urządzenia elektryczne"],
      level: 3,
      assetPath: ""),
  Question(
      id: "PLVwRwFHsGpH0Wht6A8I",
      q: "W Polsce, wartości napięć instalacji elektrycznej w budynkach mieszkalnych wynoszą obecnie:",
      a1: "230/400 V",
      a2: "220/380 V",
      a3: "110/220 V",
      a4: "230/230 V",
      labels: ["sieci niskiego napięcia"],
      level: 1,
      assetPath: ""),
  Question(
      id: "estYcpCM68CY2e6Jh78R",
      q: "Który z symboli dotyczy stopnia ochrony osłony lub obudowy urządzenia przed dostępem człowieka i wnikaniem wody?",
      a1: "IP48",
      a2: "AD2",
      a3: "IK05",
      a4: "IEC529",
      labels: ["urządzenia elektryczne"],
      level: 2,
      assetPath: ""),
  Question(
      id: "BVdNs3VTxzyXEvNqbTPR",
      q: "Barwą jasnoniebieską na całej długości i dodatkowo zielono-żółtymi znacznikami przy końcach może być oznaczany przewód",
      a1: "ochronno-neutralny PEN",
      a2: "ochronny PE",
      a3: "neturalny N",
      a4: "fazowy L",
      labels: ["sieci niskiego napięcia"],
      level: 2,
      assetPath: ""),
  Question(
      id: "byUIns8tvzPsYtTEqGDQ",
      q: "W przewodzie pięciożyłowym wyposażonym w żyłę ochronną o barwie żółto-zielonej, poszczególne żyły fazowe powinny być oznaczone barwami:",
      a1: "brązową, czarną, szarą",
      a2: "brązową, czarną, czerwoną",
      a3: "czarną, szarą, białą",
      a4: "żółtą, zieloną, białą",
      labels: [""],
      level: 1,
      assetPath: ""),
  Question(
      id: "hwJtge8rwYPwImfFbqxj",
      q: "Do grupy bardzo niskich napięć (ang. Extra-low voltage) NIE należy",
      a1: "NELV",
      a2: "PELV",
      a3: "SELV",
      a4: "FELV",
      labels: ["definicje"],
      level: 2,
      assetPath: ""),
  Question(
      id: "hkm0QzhpEaQMWTYtyCcI",
      q: "Część przewodząca urządzenia lub instalacji elektrycznej, która może znaleźć się pod napięciem w warunkach normalnej pracy to:",
      a1: "część czynna",
      a2: "część bierna",
      a3: "część ekwipotencjalna",
      a4: "część izolowana",
      labels: ["ochrona przeciwporażeniowa"],
      level: 2,
      assetPath: ""),
  Question(
      id: "kgrlDOI8acwC0mFrTz1k",
      q: "Dotknięcie przez człowieka lub zwierzę części czynnych to:",
      a1: "dotyk bezpośredni",
      a2: "dotyk pośredni",
      a3: "dotyk udarowy",
      a4: "dotyk przejściowy",
      labels: ["definicje"],
      level: 1,
      assetPath: ""),
  Question(
      id: "hZI5ovUdlqGYBGjmsVEb",
      q: "Przewód ochronny PE nie może łączyć części przewodzących dostępnych z:",
      a1: "częścią czynną",
      a2: "punktem neutralnym transformatora",
      a3: "uziomem ochronnym",
      a4: "główną szyną uziemiającą",
      labels: ["sieci niskiego napięcia"],
      level: 3,
      assetPath: ""),
];
